const topicNames = {
  "time": "Time & routines",
  "family": "Family & people",
  "home": "Home & furniture",
  "kitchen": "Kitchen & tableware",
  "food": "Food, drink & cooking",
  "clothing": "Clothing & accessories",
  "directions": "Directions & location",
  "travel": "Travel & transport",
  "places": "Places & geography",
  "weather": "Weather & nature",
  "animals": "Animals",
  "work": "Jobs & work",
  "education": "School & learning",
  "money": "Shopping & money",
  "health": "Body, health & safety",
  "feelings": "Feelings & personality",
  "colours": "Colours",
  "descriptions": "Size, qualities & materials",
  "numbers": "Numbers & quantities",
  "media": "Media, technology & leisure",
  "conversation": "Conversation & questions",
  "society": "Society & history",
  "actions": "Everyday actions",
  "sentence-building": "Pronouns & linking words"
};
