const topicNames = {
  "time": "Time & routines",
  "family": "Family & people",
  "home": "Home, furniture & kitchen",
  "food": "Food, drink & cooking",
  "clothing": "Clothing & accessories",
  "directions": "Places, directions & location",
  "travel": "Travel & transport",
  "weather": "Weather & nature",
  "animals": "Animals",
  "work": "Jobs & work",
  "education": "School & learning",
  "money": "Shopping & money",
  "health": "Body, health & safety",
  "feelings": "Feelings & personality",
  "colours": "Colours",
  "descriptions": "Size, qualities & materials",
  "numbers": "Numbers & quantities",
  "media": "Media, technology & leisure",
  "conversation": "Conversation & questions",
  "verbs": "Verbs: roots & present",
  "endings": "Possessive & object endings",
  "sentence-building": "Linking words"
};
